# <font color = orange> <strong> <center> <u> Build a Recommendation System </center> </strong> </font>

<strong>Expectations and Outcome </strong>
1. Built at least two types of recommendation systems: user-based and item-based recommendation systems
2. Evaluated both the types of recommendation systems and selected one based on performance. Provided detailed reasons for selecting the recommendation system
3. Recommended the top 20 products for the username selected by the user based on the recommendation system built
4. Predicted the sentiment (positive or negative) of all the reviews in the train data set of the top 20 recommended products for a user. For each of the 20 products recommended, found the percentage of positive sentiments for all the reviews of each product.
5. Filtered out the top 5 products with the highest percentage of positive reviews.


We will build the following two recommendation systems:

1. User-based Recommendation System
2. Item-based Recommendation System

Once both systems are built, we will analyze their performance and select the one that is best suited for our use case.

After identifying the best recommendation system, the next task will be to recommend 20 products that a user is most likely to purchase based on their ratings.

In [1]:
import pandas as pd
import re
import time
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter
from datetime import datetime
import warnings
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', 300)
pd.set_option("display.precision", 2)

In [2]:
# importing dataset
df_reviews = pd.read_csv("sample30.csv")
df_reviews.head()

id            brand  \
0  AV13O1A8GV-KLJ3akUyj  Universal Music   
1  AV14LG0R-jtxr-f38QfS         Lundberg   
2  AV14LG0R-jtxr-f38QfS         Lundberg   
3  AV16khLE-jtxr-f38VFn              K-Y   
4  AV16khLE-jtxr-f38VFn              K-Y   

                                                                                                                                                       categories  \
0  Movies, Music & Books,Music,R&b,Movies & TV,Movie Bundles & Collections,CDs & Vinyl,Rap & Hip-Hop,Bass,Music on CD or Vinyl,Rap,Hip-Hop,Mainstream Rap,Pop Rap   
1                                                                                    Food,Packaged Foods,Snacks,Crackers,Snacks, Cookies & Chips,Rice Cakes,Cakes   
2                                                                                    Food,Packaged Foods,Snacks,Crackers,Snacks, Cookies & Chips,Rice Cakes,Cakes   
3                                                                           Personal Care,Medicine Cabinet,Lubricant/Spermicide,Health,Sexual Wellness,Lubricants   
4                                                                           Personal Care,Medicine Cabinet,Lubricant/Spermicide,Health,Sexual Wellness,Lubricants   

                         manufacturer  \
0  Universal Music Group / Cash Money   
1                            Lundberg   
2                            Lundberg   
3                                 K-Y   
4                                 K-Y   

                                         name              reviews_date  \
0   Pink Friday: Roman Reloaded Re-Up (w/dvd)  2012-11-30T06:21:45.000Z   
1  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
2  Lundberg Organic Cinnamon Toast Rice Cakes  2017-07-09T00:00:00.000Z   
3            K-Y Love Sensuality Pleasure Gel  2016-01-06T00:00:00.000Z   
4            K-Y Love Sensuality Pleasure Gel  2016-12-21T00:00:00.000Z   

  reviews_didPurchase reviews_doRecommend  reviews_rating  \
0                 NaN                 NaN               5   
1                True                 NaN               5   
2                True                 NaN               5   
3               False               False               1   
4               False               False               1   

                                                                                                                                                                                                                                                                                                  reviews_text  \
0                                                                                                    i love this album. it's very good. more to the hip hop side than her current pop sound.. SO HYPE! i listen to this everyday at the gym! i give it 5star rating all the way. her metaphors are just crazy.   
1                                                                                                                                                                                                                                               Good flavor. This review was collected as part of a promotion.   
2                                                                                                                                                                                                                                                                                                 Good flavor.   
3  I read through the reviews on here before looking in to buying one of the couples lubricants, and was ultimately disappointed that it didn't even live up to the reviews I had read. For starters, neither my boyfriend nor I could notice any sort of enhanced or 'captivating' sensation. What we did ...   
4                                                                                                                                                                         

In [3]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   id                    30000 non-null  object
 1   brand                 30000 non-null  object
 2   categories            30000 non-null  object
 3   manufacturer          29859 non-null  object
 4   name                  30000 non-null  object
 5   reviews_date          29954 non-null  object
 6   reviews_didPurchase   15932 non-null  object
 7   reviews_doRecommend   27430 non-null  object
 8   reviews_rating        30000 non-null  int64 
 9   reviews_text          30000 non-null  object
 10  reviews_title         29810 non-null  object
 11  reviews_userCity      1929 non-null   object
 12  reviews_userProvince  170 non-null    object
 13  reviews_username      29937 non-null  object
 14  user_sentiment        29999 non-null  object
dtypes: int64(1), object(14)
memory usage

In [4]:
df_recommendation = df_reviews[["id", "name", "reviews_rating", "reviews_username"]]


In [5]:
df_recommendation.head()

id                                        name  \
0  AV13O1A8GV-KLJ3akUyj   Pink Friday: Roman Reloaded Re-Up (w/dvd)   
1  AV14LG0R-jtxr-f38QfS  Lundberg Organic Cinnamon Toast Rice Cakes   
2  AV14LG0R-jtxr-f38QfS  Lundberg Organic Cinnamon Toast Rice Cakes   
3  AV16khLE-jtxr-f38VFn            K-Y Love Sensuality Pleasure Gel   
4  AV16khLE-jtxr-f38VFn            K-Y Love Sensuality Pleasure Gel   

   reviews_rating reviews_username  
0               5           joshua  
1               5        dorothy w  
2               5        dorothy w  
3               1          rebecca  
4               1        walker557

In [6]:
from sklearn.model_selection import train_test_split # Import the train_test_split function


In [7]:
train, test = train_test_split(df_recommendation, test_size=0.25, random_state=42)


In [8]:
print(train.shape)
print(test.shape)

(22500, 4)
(7500, 4)


In [9]:
product_column = "id"
user_column = "reviews_username"
value_column = "reviews_rating"

In [10]:
# Pivot the train ratings' dataset into matrix format in which columns are product names and the rows are user names.
df_pivot = pd.pivot_table(train,index=user_column, columns = product_column, values = value_column).fillna(0)
df_pivot.head(10)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   
1085                               0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   
1085                               0.0                   0.0   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   
1085                               0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   
1085                               0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
08dallas                           0.0                   0.0   
09mommy11                          0.0                   0.0   
1.11E+24                           0.0                   0.0   
1085                               0.0                   0.0   

id                AV1YnUMYglJLPUi8IJpK  AV1Ynb3bglJLPUi8IJxJ  \
reviews_username                                               
00dog3                     

### Creating dummy train and test


In [11]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [12]:
dummy_train.head()


id  \
21177  AVpfm8yiLJeJML43AYyu   
23942  AVpfPaoqLJeJML435Xk9   
1247   AV1YneDPglJLPUi8IJyQ   
23622  AVpfPaoqLJeJML435Xk9   
28454  AVpftikC1cnluZ0-p31V   

                                                                         name  \
21177                               Nexxus Exxtra Gel Style Creation Sculptor   
23942         Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd   
1247       Finish Quantum Dishwasher Detergent, Lemon Sparkle Scent, 45 Count   
23622         Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd   
28454  Storkcraft Tuscany Glider and Ottoman, Beige Cushions, Espresso Finish   

       reviews_rating reviews_username  
21177               1          bobdigi  
23942               4          skeeter  
1247                5          mruduka  
23622               4       kiddro3523  
28454               1        newwmomma

In [13]:
# The products not rated by user is marked as 1 for prediction.
dummy_train[value_column] = dummy_train[value_column].apply(lambda x: 0 if x>=1 else 1)

In [14]:
# Pivot the train ratings' dataset into matrix format in which columns are product names and the rows are user names.
dummy_train = pd.pivot_table(dummy_train,index=user_column, columns = product_column, values = value_column).fillna(1)
dummy_train.head(10)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02deuce                            1.0                   1.0   
0325home                           1.0                   1.0   
06stidriver                        1.0                   1.0   
08dallas                           1.0                   1.0   
09mommy11                          1.0                   1.0   
1.11E+24                           1.0                   1.0   
1085                               1.0                   1.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02deuce                            1.0                   1.0   
0325home                           1.0                   1.0   
06stidriver                        1.0                   1.0   
08dallas                           1.0                   1.0   
09mommy11                          1.0                   1.0   
1.11E+24                           1.0                   1.0   
1085                               1.0                   1.0   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02deuce                            1.0                   1.0   
0325home                           1.0                   1.0   
06stidriver                        1.0                   1.0   
08dallas                           1.0                   1.0   
09mommy11                          1.0                   1.0   
1.11E+24                           1.0                   1.0   
1085                               1.0                   1.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02deuce                            1.0                   1.0   
0325home                           1.0                   1.0   
06stidriver                        1.0                   1.0   
08dallas                           1.0                   1.0   
09mommy11                          1.0                   1.0   
1.11E+24                           1.0                   1.0   
1085                               1.0                   1.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
02deuce                            1.0                   1.0   
0325home                           1.0                   1.0   
06stidriver                        1.0                   1.0   
08dallas                           1.0                   1.0   
09mommy11                          1.0                   1.0   
1.11E+24                           1.0                   1.0   
1085                               1.0                   1.0   

id                AV1YnUMYglJLPUi8IJpK  AV1Ynb3bglJLPUi8IJxJ  \
reviews_username                                               
00dog3                     

**Cosine Similarity**

Cosine Similarity is a measurement that quantifies the similarity between two vectors [Which is `reviews_rating` in this case]

**Adjusted Cosine**

Adjusted cosine similarity is a modified version of vector-based similarity where we incorporate the fact that different users have different ratings schemes. In other words, some users might rate items highly in general, and others might give items lower ratings as a preference. To handle this nature from rating given by user , we subtract average ratings for each user from each user's rating for different products.



### User similarity matrix


In [15]:
df_pivot.index.nunique()


19380

In [16]:
from sklearn.metrics.pairwise import pairwise_distances, cosine_similarity


In [17]:
#using cosine_similarity function to compute the distance.
user_correlation = cosine_similarity(df_pivot)
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)
print(user_correlation.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 1.]]
(19380, 19380)


#### Prediction User-User


Doing the prediction for the users which are positively related with other users, and not the users which are negatively related as we are interested in the users which are more similar to the current users. So, we will be ignoring the correlation for values less than 0.

In [18]:
#filtering out the user_correlation that are negatively correlated
user_correlation[user_correlation<0]=0
user_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 1.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 1.]])

Rating predicted by the user (for products rated as well as not rated) is the weighted sum of correlation with the product rating (as present in the rating dataset).

In [19]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 2.39045722, ..., 1.81848242, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 3.53553391, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 3.53553391, 0.        ,
        0.        ]])

In [20]:
#since we are interested in products that are not rated by the user, we multiply with dummy train to make it zero
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                            0.00                  0.00   
00sab00                           0.00                 11.94   
01impala                          2.39                 15.68   
02deuce                           2.39                 15.68   
0325home                          0.00                 10.01   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             0.0                  0.00   
00sab00                            0.0                  2.22   
01impala                           0.0                  0.00   
02deuce                            0.0                  0.00   
0325home                           0.0                  2.89   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
00dog3                            0.00                  0.00   
00sab00                           0.00                  0.00   
01impala                          2.61                  0.00   
02deuce                           2.61                  0.00   
0325home                          6.94                  4.44   

id                AV1YnUMYglJLPUi8IJpK  AV1Ynb3bglJLPUi8IJxJ  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YneDPglJLPUi8IJyQ  AV1YpiJvvKc47QAVguxy  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YqAaMGV-KLJ3adiDj  AV1Ys0kTvKc47QAVgx1C  \
reviews_username                                               
00dog3                            0.00                  0.00   
00sab00                           0.00                  3.25   
01impala                          1.85                  3.81   
02deuce                           1.85                  3.81   
0325home                          0.00                  0.00   

id                AV1YtGjdglJLPUi8IOfJ  AV1ZSp2uglJLPUi8IQFy  \
reviews_username                                               
00dog3                            0.00                  0.00   
00sab00                           0.91                  0.00   
01impala                          0.00                  5.41   
02deuce                           0.00                  5.41   
0325home                

#### Find Top 20 products that a user is most likely to purchase

In [21]:
user_input = "08dallas"
recommendations = user_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
recommendations

id
AVpfRTh1ilAPnD_xYic2    23.26
AVpfPaoqLJeJML435Xk9    22.26
AVpf0eb2LJeJML43EVSt    12.06
AVpf3VOfilAPnD_xjpun     7.56
AVpf2tw1ilAPnD_xjflC     7.20
AVpe41TqilAPnD_xQH3d     5.87
AVpfR5m0LJeJML436K3W     2.89
AVpfJP1C1cnluZ0-e3Xy     2.89
AVpfoSS51cnluZ0-oVH9     2.89
AVpf7I3i1cnluZ0-tnL6     2.87
AVpfM_ytilAPnD_xXIJb     2.46
AVpfhxaELJeJML43-zsM     2.02
AVpe8xjUilAPnD_xRkxC     2.02
AVpfH2Rx1cnluZ0-eYtu     2.02
AVpfm8yiLJeJML43AYyu     1.96
AVpfOmKwLJeJML435GM7     1.55
AV1Yn94nvKc47QAVgtst     1.55
AVpfPnrU1cnluZ0-g9rL     1.55
AVpf385g1cnluZ0-s0_t     1.24
AV1YGDqsGV-KLJ3adc-O     0.61
Name: 08dallas, dtype: float64

In [22]:
#display the top 20 product id, name and similarity_score
final_recommendations = pd.DataFrame({'product_id': recommendations.index, 'similarity_score' : recommendations})
final_recommendations.reset_index(drop=True)
pd.merge(final_recommendations, train, on="id")[["id", "name", "similarity_score"]].drop_duplicates()

id  \
0      AVpfRTh1ilAPnD_xYic2   
873    AVpfPaoqLJeJML435Xk9   
3350   AVpf0eb2LJeJML43EVSt   
3989   AVpf3VOfilAPnD_xjpun   
10347  AVpf2tw1ilAPnD_xjflC   
10864  AVpe41TqilAPnD_xQH3d   
11437  AVpfR5m0LJeJML436K3W   
11588  AVpfJP1C1cnluZ0-e3Xy   
13136  AVpfoSS51cnluZ0-oVH9   
13185  AVpf7I3i1cnluZ0-tnL6   
13208  AVpfM_ytilAPnD_xXIJb   
13403  AVpfhxaELJeJML43-zsM   
13405  AVpe8xjUilAPnD_xRkxC   
13417  AVpfH2Rx1cnluZ0-eYtu   
13420  AVpfm8yiLJeJML43AYyu   
13942  AVpfOmKwLJeJML435GM7   
14221  AV1Yn94nvKc47QAVgtst   
14243  AVpfPnrU1cnluZ0-g9rL   
14386  AVpf385g1cnluZ0-s0_t   
14533  AV1YGDqsGV-KLJ3adc-O   

                                                                                 name  \
0                 Planes: Fire Rescue (2 Discs) (includes Digital Copy) (blu-Ray/dvd)   
873                   Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd   
3350                                   The Resident Evil Collection 5 Discs (blu-Ray)   
3989                        Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total   
10347                                                Red (special Edition) (dvdvideo)   
10864                                    Mike Dave Need Wedding Dates (dvd + Digital)   
11437                                                  Jason Aldean - They Don't Know   
11588                                            Clorox Disinfecting Bathroom Cleaner   
13136                              Cheetos Crunchy Flamin' Hot Cheese Flavored Snacks   
13185                      Mrs. Meyer's174 Lemon Verbena Laundry Scent Booster - 18oz   
13208                                               Tostitos Bite Size Tortilla Chips   
13403                              Batherapy Natural Mineral Bath Sport Liquid, 16 oz   
13405                                            The Honest Company Laundry Detergent   
13417  Lynk Professional174 Pull Out Cutting Board Bakeware Sliding Cabinet Organizer   
13420                                       Nexxus Exxtra Gel Style Creation Sculptor   
13942                        Clear Scalp & Hair Therapy Total Care Nourishing Shampoo   
14221                                                        CeraVe SA Renewing Cream   
14243                    Stargate (ws) (ultimate Edition) (director's Cut) (dvdvideo)   
14386                                                          Hormel Chili, No Beans   
14533                           Windex Original Glass Cleaner Refill 67.6oz (2 Liter)   

       similarity_score  
0                 23.26  
873               22.26  
3350              12.06  
3989               7.56  
10347              7.20  
10864              5.87  
11437              2.89  
11588              2.89  
13136              2.89  
13185              2.87  
13208              2.46  
13403              2.02  
13405              2.02  
13417              2.02  
13420              1.96  
13942              1.55  
14221              1.55  
14243              1.55  
14386              1.24  
14533              0.61

#### Evaluation User-User


Evaluation will we same as you have seen above for the prediction. The only difference being, you will evaluate for the product already rated by the user insead of predicting it for the product not rated by the user.

In [23]:
# Find out the common users of test and train dataset.
common = test[test.reviews_username.isin(train.reviews_username)]
common.shape

(1776, 4)

In [24]:
common.head()


id  \
2308   AVpe41TqilAPnD_xQH3d   
22404  AVpfOmKwLJeJML435GM7   
11311  AVpf3VOfilAPnD_xjpun   
19043  AVpfJP1C1cnluZ0-e3Xy   
9482   AVpf3VOfilAPnD_xjpun   

                                                            name  \
2308                Mike Dave Need Wedding Dates (dvd + Digital)   
22404   Clear Scalp & Hair Therapy Total Care Nourishing Shampoo   
11311  Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total   
19043                       Clorox Disinfecting Bathroom Cleaner   
9482   Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total   

       reviews_rating reviews_username  
2308                5        iplsports  
22404               1            crysv  
11311               5      billybob789  
19043               5             fatz  
9482                5      natalie4717

In [25]:
# convert into the user-movie matrix.
common_user_based_matrix = pd.pivot_table(common,index=user_column, columns = product_column, values = value_column)
common_user_based_matrix.head()

id                       AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1YlENIglJLPUi8IHsX  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1Ymf_rglJLPUi8II2v  AV1YneDPglJLPUi8IJyQ  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1Ys0kTvKc47QAVgx1C  AV1YtGjdglJLPUi8IOfJ  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1ZT7GLglJLPUi8IQLI  AV1ZVIgy-jtxr-f31W9N  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1h6Gu0glJLPUi8IjA_  AV1l8zRZvKc47QAVhnAv  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AVpe-ltS1cnluZ0-bL8w  AVpe31o71cnluZ0-YrSD  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AVpe41TqilAPnD_xQH3d  AVpe4pnBilAPnD_xQDeb  \
reviews_username                                                      
00sab00                                   1.0                   NaN   
1234                                      5.0                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id              

In [26]:
# Convert the user_correlation matrix into dataframe.
user_correlation_df = pd.DataFrame(user_correlation)
user_correlation_df.head()

0      1      2      3      4      5      6      7      8      9      \
0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
2    0.0    0.0    1.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
3    0.0    0.0    1.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
4    0.0    0.0    0.0    0.0    1.0    1.0    0.0    0.0    1.0    0.0   

   10     11     12     13     14     15     16     17     18     19     \
0    0.0    0.0   0.00    0.0    0.0    0.0   0.00    0.0    0.0    0.0   
1    0.0    0.0   0.00    0.0    0.0    1.0   0.00    0.0    0.0    0.0   
2    0.0    0.0   0.71    0.0    0.0    0.0   0.71    1.0    0.0    0.0   
3    0.0    0.0   0.71    0.0    0.0    0.0   0.71    1.0    0.0    0.0   
4    0.0    0.0   0.71    1.0    1.0    0.0   0.00    0.0    1.0    1.0   

   20     21     22     23     24     25     26     27     28     29     \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4    0.0    0.0    0.0    0.0    1.0    1.0    0.0    0.0    0.0    0.0   

   30     31     32     33     34     35     36     37     38     39     \
0    0.0    0.0    0.0   0.00    0.0    0.0    0.0    0.0    0.0    0.0   
1    0.0    0.0    0.0   0.00    0.0    0.0    0.0    0.0    0.0    0.0   
2    0.0    0.0    0.0   0.51    1.0    0.0    0.0    1.0    0.0    0.0   
3    0.0    0.0    0.0   0.51    1.0    0.0    0.0    1.0    0.0    0.0   
4    1.0    0.0    0.0   0.00    0.0    0.0    0.0    0.0    0.0    0.0   

   40     41     42     43     44     45     46     47     48     49     \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0   
2    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
3    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
4    0.0    1.0    0.0    1.0    1.0    0.0    0.0    0.0    0.0    0.0   

   50     51     52     53     54     55     56     57     58     59     \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    1.0    0.0   
3    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    1.0    0.0   
4    0.0    0.0    0.0    1.0    0.0    1.0    0.0    0.0    0.0    0.0   

   60     61     62     63     64     65     66     67     68     69     \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
4    0.0    1.0    0.0    1.0    0.0    1.0    0.0    0.0    0.0    0.0   

   70     71     72     73     74     75     76     77     78     79     \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0   
4    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

   80     81     82     83     84     85     86     87     88     89     \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1    0.0    0.0    0.0    0.0    1.0    0.0    1.0    0.0    0.0    0.0   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4    1.0    0.0    0

In [27]:
user_correlation_df[user_column] = df_pivot.index
user_correlation_df.set_index(user_column,inplace=True)
user_correlation_df.head()

0      1      2      3      4      5      6      7      \
reviews_username                                                           
00dog3              1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00             0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
01impala            0.0    0.0    1.0    1.0    0.0    0.0    0.0    0.0   
02deuce             0.0    0.0    1.0    1.0    0.0    0.0    0.0    0.0   
0325home            0.0    0.0    0.0    0.0    1.0    1.0    0.0    0.0   

                  8      9      10     11     12     13     14     15     \
reviews_username                                                           
00dog3              0.0    0.0    0.0    0.0   0.00    0.0    0.0    0.0   
00sab00             0.0    1.0    0.0    0.0   0.00    0.0    0.0    1.0   
01impala            0.0    0.0    0.0    0.0   0.71    0.0    0.0    0.0   
02deuce             0.0    0.0    0.0    0.0   0.71    0.0    0.0    0.0   
0325home            1.0    0.0    0.0    0.0   0.71    1.0    1.0    0.0   

                  16     17     18     19     20     21     22     23     \
reviews_username                                                           
00dog3             0.00    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00            0.00    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
01impala           0.71    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
02deuce            0.71    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
0325home           0.00    0.0    1.0    1.0    0.0    0.0    0.0    0.0   

                  24     25     26     27     28     29     30     31     \
reviews_username                                                           
00dog3              0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
01impala            0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
02deuce             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
0325home            1.0    1.0    0.0    0.0    0.0    0.0    1.0    0.0   

                  32     33     34     35     36     37     38     39     \
reviews_username                                                           
00dog3              0.0   0.00    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00             0.0   0.00    0.0    0.0    0.0    0.0    0.0    0.0   
01impala            0.0   0.51    1.0    0.0    0.0    1.0    0.0    0.0   
02deuce             0.0   0.51    1.0    0.0    0.0    1.0    0.0    0.0   
0325home            0.0   0.00    0.0    0.0    0.0    0.0    0.0    0.0   

                  40     41     42     43     44     45     46     47     \
reviews_username                                                           
00dog3              0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00             0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0   
01impala            0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0   
02deuce             0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0   
0325home            0.0    1.0    0.0    1.0    1.0    0.0    0.0    0.0   

                  48     49     50     51     52     53     54     55     \
reviews_username                                                           
00dog3              0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00             0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
01impala            0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
02deuce             0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
0325home            0.0    0.0    0.0    0.0    0.0    1.0    0.0    1.0   

                  56     57     58     59     60     61     62     63     \
reviews_username                                                           
00dog3              0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
00sab00             0.0    0.0    0.0    0.0    0.0    0.0 

In [28]:
list_name = common.reviews_username.tolist()

user_correlation_df.columns = df_pivot.index.tolist()
user_correlation_df_1 =  user_correlation_df[user_correlation_df.index.isin(list_name)]

In [29]:

user_correlation_df_2 = user_correlation_df_1.T[user_correlation_df_1.T.index.isin(list_name)]
user_correlation_df_3 = user_correlation_df_2.T
user_correlation_df_3[user_correlation_df_3<0]=0

common_user_predicted_ratings = np.dot(user_correlation_df_3, common_user_based_matrix.fillna(0))
common_user_predicted_ratings

array([[ 0.        ,  1.85485666,  0.        , ...,  1.85485666,
         2.29174624,  1.        ],
       [ 3.10190162, 10.91070777,  0.        , ...,  1.18042355,
         0.        ,  3.53553391],
       [ 0.        ,  3.12347524,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.5       ,  4.92031173,  0.        , ...,  0.        ,
         0.        ,  5.        ],
       [ 0.        ,  3.12347524,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 2.33205081,  6.3058555 ,  0.        , ...,  1.0016226 ,
         0.        ,  0.        ]])

In [30]:
user_correlation_df_1.shape
(1530, 19427)

(1530, 19427)

In [31]:
dummy_test = common.copy()

dummy_test[value_column] = dummy_test[value_column].apply(lambda x: 1 if x>=1 else 0)
dummy_test = pd.pivot_table(dummy_test,index=user_column, columns = product_column, values = value_column).fillna(0)


In [32]:
dummy_test.shape


(1518, 119)

In [33]:
common_user_based_matrix.head()


id                       AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1YlENIglJLPUi8IHsX  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1Ymf_rglJLPUi8II2v  AV1YneDPglJLPUi8IJyQ  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1Ys0kTvKc47QAVgx1C  AV1YtGjdglJLPUi8IOfJ  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1ZT7GLglJLPUi8IQLI  AV1ZVIgy-jtxr-f31W9N  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AV1h6Gu0glJLPUi8IjA_  AV1l8zRZvKc47QAVhnAv  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AVpe-ltS1cnluZ0-bL8w  AVpe31o71cnluZ0-YrSD  \
reviews_username                                                      
00sab00                                   NaN                   NaN   
1234                                      NaN                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id                       AVpe41TqilAPnD_xQH3d  AVpe4pnBilAPnD_xQDeb  \
reviews_username                                                      
00sab00                                   1.0                   NaN   
1234                                      5.0                   NaN   
143st                                     NaN                   NaN   
23jen                                     NaN                   NaN   
4 rooms 1 dog lotsa fur                   NaN                   NaN   

id              

In [34]:
common_user_predicted_ratings = np.multiply(common_user_predicted_ratings,dummy_test)


In [35]:
common_user_predicted_ratings.head()


id                       AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                                      
00sab00                                   0.0                   0.0   
1234                                      0.0                   0.0   
143st                                     0.0                   0.0   
23jen                                     0.0                   0.0   
4 rooms 1 dog lotsa fur                   0.0                   0.0   

id                       AV1YlENIglJLPUi8IHsX  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                                      
00sab00                                   0.0                   0.0   
1234                                      0.0                   0.0   
143st                                     0.0                   0.0   
23jen                                     0.0                   0.0   
4 rooms 1 dog lotsa fur                   0.0                   0.0   

id                       AV1Ymf_rglJLPUi8II2v  AV1YneDPglJLPUi8IJyQ  \
reviews_username                                                      
00sab00                                   0.0                   0.0   
1234                                      0.0                   0.0   
143st                                     0.0                   0.0   
23jen                                     0.0                   0.0   
4 rooms 1 dog lotsa fur                   0.0                   0.0   

id                       AV1Ys0kTvKc47QAVgx1C  AV1YtGjdglJLPUi8IOfJ  \
reviews_username                                                      
00sab00                                   0.0                   0.0   
1234                                      0.0                   0.0   
143st                                     0.0                   0.0   
23jen                                     0.0                   0.0   
4 rooms 1 dog lotsa fur                   0.0                   0.0   

id                       AV1ZT7GLglJLPUi8IQLI  AV1ZVIgy-jtxr-f31W9N  \
reviews_username                                                      
00sab00                                   0.0                   0.0   
1234                                      0.0                   0.0   
143st                                     0.0                   0.0   
23jen                                     0.0                   0.0   
4 rooms 1 dog lotsa fur                   0.0                   0.0   

id                       AV1h6Gu0glJLPUi8IjA_  AV1l8zRZvKc47QAVhnAv  \
reviews_username                                                      
00sab00                                   0.0                   0.0   
1234                                      0.0                   0.0   
143st                                     0.0                   0.0   
23jen                                     0.0                   0.0   
4 rooms 1 dog lotsa fur                   0.0                   0.0   

id                       AVpe-ltS1cnluZ0-bL8w  AVpe31o71cnluZ0-YrSD  \
reviews_username                                                      
00sab00                                   0.0                   0.0   
1234                                      0.0                   0.0   
143st                                     0.0                   0.0   
23jen                                     0.0                   0.0   
4 rooms 1 dog lotsa fur                   0.0                   0.0   

id                       AVpe41TqilAPnD_xQH3d  AVpe4pnBilAPnD_xQDeb  \
reviews_username                                                      
00sab00                                 43.20                   0.0   
1234                                    38.26                   0.0   
143st                                    0.00                   0.0   
23jen                                    0.00                   0.0   
4 rooms 1 dog lotsa fur                  0.00                   0.0   

id              

* Calculating the RMSE for only the products rated by user.
* For RMSE, normalising the rating to (1,5) range.

In [36]:
#calculate RMSE

from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_user_predicted_ratings.copy()
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [37]:
common_ = pd.pivot_table(common,index=user_column, columns = product_column, values = value_column)


RMSE (Root Mean Square Error) for User-User recommendation system

In [38]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))
rmse_user_user = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse_user_user)

2.161605143981965


### Item Based Similarity


Taking the transpose of the rating matrix to normalize the rating around the mean for different Product ID. In the user based similarity, we had taken mean for each user instead of each product.

In [39]:
df_pivot = pd.pivot_table(train,
    index=product_column,
    columns=user_column,
    values=value_column
)

df_pivot.head()

reviews_username      00dog3  00sab00  01impala  02deuce  0325home  \
id                                                                   
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN      NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  1085  10ten  \
id                                                                              
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN   NaN    NaN   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN   NaN    NaN   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN   NaN    NaN   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN   NaN    NaN   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN   NaN    NaN   

reviews_username      11111111aaaaaaaaaaaaaaaaa  1234  1234561  1234567  \
id                                                                        
AV13O1A8GV-KLJ3akUyj                        NaN   NaN      NaN      NaN   
AV14LG0R-jtxr-f38QfS                        NaN   NaN      NaN      NaN   
AV16khLE-jtxr-f38VFn                        NaN   NaN      NaN      NaN   
AV1YGDqsGV-KLJ3adc-O                        NaN   NaN      NaN      NaN   
AV1YIch7GV-KLJ3addeG                        NaN   NaN      NaN      NaN   

reviews_username      123cat123  123charlie  123numbers  123rs  123soccermom  \
id                                                                             
AV13O1A8GV-KLJ3akUyj        NaN         NaN         NaN    NaN           NaN   
AV14LG0R-jtxr-f38QfS        NaN         NaN         NaN    NaN           NaN   
AV16khLE-jtxr-f38VFn        NaN         NaN         NaN    NaN           NaN   
AV1YGDqsGV-KLJ3adc-O        NaN         NaN         NaN    NaN           NaN   
AV1YIch7GV-KLJ3addeG        NaN         NaN         NaN    NaN           NaN   

reviews_username      123too  127726  132457  13ld  13thfaerie  1421nikki  \
id                                                                          
AV13O1A8GV-KLJ3akUyj     NaN     NaN     NaN   NaN         NaN        NaN   
AV14LG0R-jtxr-f38QfS     NaN     NaN     NaN   NaN         NaN        NaN   
AV16khLE-jtxr-f38VFn     NaN     NaN     NaN   NaN         NaN        NaN   
AV1YGDqsGV-KLJ3adc-O     NaN     NaN     NaN   NaN         NaN        NaN   
AV1YIch7GV-KLJ3addeG     NaN     NaN     NaN   NaN         NaN        NaN   

reviews_username      143st  1515  15425shopper  1616  1753  17roses  \
id                                                                     
AV13O1A8GV-KLJ3akUyj    NaN   NaN           NaN   NaN   NaN      NaN   
AV14LG0R-jtxr-f38QfS    NaN   NaN           NaN   NaN   NaN      NaN   
AV16khLE-jtxr-f38VFn    NaN   NaN           NaN   NaN   NaN      NaN   
AV1YGDqsGV-KLJ3adc-O    NaN   NaN           NaN   NaN   NaN      NaN   
AV1YIch7GV-KLJ3addeG    NaN   NaN           NaN   NaN   NaN      NaN   

reviews_username      1863philly  1943  1970  1979edes  1992firebirdgirl  \
id                                                                         
AV13O1A8GV-KLJ3akUyj         NaN   NaN   NaN       NaN               NaN   
AV14LG0R-jtxr-f38QfS         NaN   NaN   NaN       NaN               NaN   
AV16khLE-jtxr-f38VFn         NaN   NaN   NaN       NaN               NaN   
AV1YGDqsGV-KLJ3adc-O         NaN   NaN   NaN       NaN               NaN   
AV1YIch7GV-KLJ3addeG         NaN   NaN   NaN       NaN               NaN   

reviews_username      19bubba67  19granny  1awesome1  1boomer  1buzymom  \
id                                                                        
AV13O1A8GV-KLJ3akUyj        NaN       NaN        NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS        NaN       NaN        Na

In [40]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [41]:
# Item Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [42]:
item_correlation[item_correlation<0]=0
item_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

#### Prediction - item-item


In [43]:
item_predicted_ratings = np.dot((df_pivot.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.00051462, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.00102925, 0.        ,
        0.        ]])


Filtering the rating only for the products not rated by the user for recommendation


In [44]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
00dog3                             0.0              0.00e+00   
00sab00                            0.0              8.91e-03   
01impala                           0.0              0.00e+00   
02deuce                            0.0              0.00e+00   
0325home                           0.0              0.00e+00   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
00dog3                             0.0              0.00e+00   
00sab00                            0.0              0.00e+00   
01impala                           0.0              0.00e+00   
02deuce                            0.0              0.00e+00   
0325home                           0.0              2.12e-03   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  \
reviews_username                                               
00dog3                        0.00e+00              0.00e+00   
00sab00                       0.00e+00              0.00e+00   
01impala                      0.00e+00              0.00e+00   
02deuce                       0.00e+00              0.00e+00   
0325home                      3.83e-03              3.65e-03   

id                AV1YnUMYglJLPUi8IJpK  AV1Ynb3bglJLPUi8IJxJ  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YneDPglJLPUi8IJyQ  AV1YpiJvvKc47QAVguxy  \
reviews_username                                               
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
02deuce                            0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YqAaMGV-KLJ3adiDj  AV1Ys0kTvKc47QAVgx1C  \
reviews_username                                               
00dog3                        0.00e+00              0.00e+00   
00sab00                       0.00e+00              0.00e+00   
01impala                      3.16e-03              7.62e-03   
02deuce                       4.22e-03              1.02e-02   
0325home                      0.00e+00              0.00e+00   

id                AV1YtGjdglJLPUi8IOfJ  AV1ZSp2uglJLPUi8IQFy  \
reviews_username                                               
00dog3                        0.00e+00                   0.0   
00sab00                       6.93e-03                   0.0   
01impala                      0.00e+00                   0.0   
02deuce                       0.00e+00                   0.0   
0325home                

#### Finding the top 20 recommendation for the user


In [45]:
# Take the user ID as input
user_input = '08dallas'
print(user_input)

08dallas


In [46]:
# Recommending the Top 5 products to the user.
item_recommendations = item_final_rating.loc[user_input].sort_values(ascending=False)[0:20]
item_recommendations

id
AVpe8xjUilAPnD_xRkxC    4.93e-02
AVpf7I3i1cnluZ0-tnL6    4.68e-02
AVpe41TqilAPnD_xQH3d    4.38e-02
AVpf0eb2LJeJML43EVSt    2.37e-02
AVpf2tw1ilAPnD_xjflC    2.27e-02
AVpf385g1cnluZ0-s0_t    1.47e-02
AVpfoSS51cnluZ0-oVH9    1.43e-02
AVpfR5m0LJeJML436K3W    1.05e-02
AVpfJP1C1cnluZ0-e3Xy    2.40e-03
AVpfPaoqLJeJML435Xk9    1.65e-03
AVpfRM8dLJeJML4358wT    0.00e+00
AVpfP-rELJeJML435jEN    0.00e+00
AVpfNVsj1cnluZ0-gNQN    0.00e+00
AVpfNWbPilAPnD_xXPR7    0.00e+00
AVpfNc9cLJeJML434tza    0.00e+00
AVpfNfEMLJeJML434uf-    0.00e+00
AVpfNglu1cnluZ0-gQ7x    0.00e+00
AVpfO5u71cnluZ0-guiN    0.00e+00
AVpfOIrkilAPnD_xXgDG    0.00e+00
AVpfOfIqLJeJML435D06    0.00e+00
Name: 08dallas, dtype: float64

In [47]:
item_final_recommendations = pd.DataFrame({'product_id': item_recommendations.index, 'similarity_score' : item_recommendations})
item_final_recommendations.reset_index(drop=True)
pd.merge(item_final_recommendations, train, on="id")[["id", "name", "similarity_score"]].drop_duplicates()


id  \
0     AVpe8xjUilAPnD_xRkxC   
12    AVpf7I3i1cnluZ0-tnL6   
35    AVpe41TqilAPnD_xQH3d   
608   AVpf0eb2LJeJML43EVSt   
1247  AVpf2tw1ilAPnD_xjflC   
1764  AVpf385g1cnluZ0-s0_t   
1911  AVpfoSS51cnluZ0-oVH9   
1960  AVpfR5m0LJeJML436K3W   
2111  AVpfJP1C1cnluZ0-e3Xy   
3659  AVpfPaoqLJeJML435Xk9   
6136  AVpfRM8dLJeJML4358wT   
6140  AVpfP-rELJeJML435jEN   
6141  AVpfNVsj1cnluZ0-gNQN   
6147  AVpfNWbPilAPnD_xXPR7   
6165  AVpfNc9cLJeJML434tza   
6172  AVpfNfEMLJeJML434uf-   
6182  AVpfNglu1cnluZ0-gQ7x   
6191  AVpfO5u71cnluZ0-guiN   
6195  AVpfOIrkilAPnD_xXgDG   
6297  AVpfOfIqLJeJML435D06   

                                                                          name  \
0                                         The Honest Company Laundry Detergent   
12                  Mrs. Meyer's174 Lemon Verbena Laundry Scent Booster - 18oz   
35                                Mike Dave Need Wedding Dates (dvd + Digital)   
608                             The Resident Evil Collection 5 Discs (blu-Ray)   
1247                                          Red (special Edition) (dvdvideo)   
1764                                                    Hormel Chili, No Beans   
1911                        Cheetos Crunchy Flamin' Hot Cheese Flavored Snacks   
1960                                            Jason Aldean - They Don't Know   
2111                                      Clorox Disinfecting Bathroom Cleaner   
3659           Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd   
6136                                  Cantu Coconut Milk Shine Hold Mist - 8oz   
6140                                            5302050 15/16 FCT/HOSE ADAPTOR   
6141  Physicians Formula Powder Palette Mineral Glow Pearls, Translucent Pearl   
6147                         Pleasant Hearth 7.5 Steel Grate, 30 5 Bar - Black   
6165                    Feit 60-Watt A19 Gu24 Base Led Light Bulb - Soft White   
6172                                                             Heiress (dvd)   
6182                            Mia Shower Curtain Green/brown - Lush Decor174   
6191                                                           Switchmas (dvd)   
6195                                                     Alex Cross (dvdvideo)   
6297                             Solo Foods Poppy Seed Cake and Pastry Filling   

      similarity_score  
0             4.93e-02  
12            4.68e-02  
35            4.38e-02  
608           2.37e-02  
1247          2.27e-02  
1764          1.47e-02  
1911          1.43e-02  
1960          1.05e-02  
2111          2.40e-03  
3659          1.65e-03  
6136          0.00e+00  
6140          0.00e+00  
6141          0.00e+00  
6147          0.00e+00  
6165          0.00e+00  
6172          0.00e+00  
6182          0.00e+00  
6191          0.00e+00  
6195          0.00e+00  
6297          0.00e+00

#### Evaluation - item-item


Evaluation will we same as we have seen above for the prediction. The only difference being, we will evaluate for the product already rated by the user insead of predicting it for the product not rated by the user.

In [48]:
common =  test[test.id.isin(train.id)]
common.shape

(7487, 4)

In [49]:
common.head(4)


id  \
2308   AVpe41TqilAPnD_xQH3d   
22404  AVpfOmKwLJeJML435GM7   
23397  AVpfPaoqLJeJML435Xk9   
25058  AVpfPaoqLJeJML435Xk9   

                                                                  name  \
2308                      Mike Dave Need Wedding Dates (dvd + Digital)   
22404         Clear Scalp & Hair Therapy Total Care Nourishing Shampoo   
23397  Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd   
25058  Godzilla 3d Includes Digital Copy Ultraviolet 3d/2d Blu-Ray/dvd   

       reviews_rating reviews_username  
2308                5        iplsports  
22404               1            crysv  
23397               4         sammhc12  
25058               5           spyder

In [50]:
common_item_based_matrix = common.pivot_table(index=product_column, columns=user_column, values=value_column)


In [51]:
item_correlation_df = pd.DataFrame(item_correlation)
item_correlation_df.head(1)

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   15   16   17   18   19   20   21   22   23   24   25   26   27   28   29   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   45   46   47   48   49   50   51   52   53   54   55   56   57   58   59   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   90   91   92   93   94   95   96   97   98   99   ...  158  159  160  161  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   162  163  164  165  166  167  168  169  170  171  172  173  174  175  176  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   177  178  179  180  181  182  183  184  185  186  187  188  189  190  191  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   192  193  194  195  196  197  198  199  200  201  202  203  204  205  206  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   207  208  209  210  211  212  213  214  215  216  217  218  219  220  221  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   222  223  224  225  226  227  228  229  230  231  232  233  234  235  236  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   237  238  239  240  241  242  243  244  245  246  247  248  249  250  251  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

   252  253  254  255  256  257  
0  0.0  0.0  0.0  0.0  0.0  0.0  

[1 rows x 258 columns]

In [52]:
item_correlation_df[product_column] = df_subtracted.index
item_correlation_df.set_index(product_column,inplace=True)
item_correlation_df.head()

0    1    2    3    4    5    6    7    8    9    10   \
id                                                                            
AV13O1A8GV-KLJ3akUyj  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV14LG0R-jtxr-f38QfS  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV16khLE-jtxr-f38VFn  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV1YGDqsGV-KLJ3adc-O  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV1YIch7GV-KLJ3addeG  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

                      11   12   13   14   15   16   17    18   19   20   \
id                                                                        
AV13O1A8GV-KLJ3akUyj  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00  0.0  0.0   
AV14LG0R-jtxr-f38QfS  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00  0.0  0.0   
AV16khLE-jtxr-f38VFn  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00  0.0  0.0   
AV1YGDqsGV-KLJ3adc-O  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.04  0.0  0.0   
AV1YIch7GV-KLJ3addeG  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00  0.0  0.0   

                           21   22   23   24   25   26   27   28   29   30   \
id                                                                            
AV13O1A8GV-KLJ3akUyj  0.00e+00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV14LG0R-jtxr-f38QfS  0.00e+00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV16khLE-jtxr-f38VFn  0.00e+00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV1YGDqsGV-KLJ3adc-O  8.39e-04  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV1YIch7GV-KLJ3addeG  0.00e+00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

                       31   32   33   34   35   36   37   38   39        40   \
id                                                                             
AV13O1A8GV-KLJ3akUyj  0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00e+00   
AV14LG0R-jtxr-f38QfS  0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00e+00   
AV16khLE-jtxr-f38VFn  0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00e+00   
AV1YGDqsGV-KLJ3adc-O  0.01  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.97e-03   
AV1YIch7GV-KLJ3addeG  0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00e+00   

                      41   42   43   44        45   46   47   48   49   50   \
id                                                                            
AV13O1A8GV-KLJ3akUyj  0.0  0.0  0.0  0.0  0.00e+00  0.0  0.0  0.0  0.0  0.0   
AV14LG0R-jtxr-f38QfS  0.0  0.0  0.0  0.0  0.00e+00  0.0  0.0  0.0  0.0  0.0   
AV16khLE-jtxr-f38VFn  0.0  0.0  0.0  0.0  0.00e+00  0.0  0.0  0.0  0.0  0.0   
AV1YGDqsGV-KLJ3adc-O  0.0  0.0  0.0  0.0  2.80e-03  0.0  0.0  0.0  0.0  0.0   
AV1YIch7GV-KLJ3addeG  0.0  0.0  0.0  0.0  0.00e+00  0.0  0.0  0.0  0.0  0.0   

                      51   52   53   54   55   56   57   58   59   60   61   \
id                                                                            
AV13O1A8GV-KLJ3akUyj  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV14LG0R-jtxr-f38QfS  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV16khLE-jtxr-f38VFn  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV1YGDqsGV-KLJ3adc-O  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
AV1YIch7GV-KLJ3addeG  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

                      62   63   64   65   66   67   68   69   70        71   \
id                                                                            
AV13O1A8GV-KLJ3akUyj  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00e+00   
AV14LG0R-jtxr-f38QfS  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00e+00   
AV16khLE-jtxr-f38VFn  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00e+00   
AV1YGDqsGV-KLJ3adc-O  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  6.95e-03   
AV1YIch7GV-KLJ3addeG  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.00e+00   

                      72   73   74   75   76   77   78   79   80   81   82   \
id                                                                            
AV13O1A

In [53]:
list_name = common.id.tolist()
item_correlation_df.columns = df_subtracted.index.tolist()

item_correlation_df_1 =  item_correlation_df[item_correlation_df.index.isin(list_name)]
item_correlation_df_2 = item_correlation_df_1.T[item_correlation_df_1.T.index.isin(list_name)]

item_correlation_df_3 = item_correlation_df_2.T
df_subtracted

reviews_username      00dog3  00sab00  01impala  02deuce  0325home  \
id                                                                   
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN      NaN       NaN   
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN      NaN       NaN   
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN      NaN       NaN   
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN      NaN       NaN   
AV1YIch7GV-KLJ3addeG     NaN      NaN       NaN      NaN       NaN   
...                      ...      ...       ...      ...       ...   
AVpfshNsLJeJML43CB8q     NaN      NaN       NaN      NaN       NaN   
AVpfthSailAPnD_xg3ON     NaN      NaN       NaN      NaN       NaN   
AVpftikC1cnluZ0-p31V     NaN      NaN       NaN      NaN       NaN   
AVpfv4TlilAPnD_xhjNS     NaN      NaN       NaN      NaN       NaN   
AVpfvieo1cnluZ0-qdnu     NaN      NaN       NaN      NaN       NaN   

reviews_username      06stidriver  08dallas  09mommy11  1.11E+24  1085  10ten  \
id                                                                              
AV13O1A8GV-KLJ3akUyj          NaN       NaN        NaN       NaN   NaN    NaN   
AV14LG0R-jtxr-f38QfS          NaN       NaN        NaN       NaN   NaN    NaN   
AV16khLE-jtxr-f38VFn          NaN       NaN        NaN       NaN   NaN    NaN   
AV1YGDqsGV-KLJ3adc-O          NaN       NaN        NaN       NaN   NaN    NaN   
AV1YIch7GV-KLJ3addeG          NaN       NaN        NaN       NaN   NaN    NaN   
...                           ...       ...        ...       ...   ...    ...   
AVpfshNsLJeJML43CB8q          NaN       NaN        NaN       NaN   NaN    NaN   
AVpfthSailAPnD_xg3ON          NaN       NaN        NaN       NaN   NaN    NaN   
AVpftikC1cnluZ0-p31V          NaN       NaN        NaN       NaN   NaN    NaN   
AVpfv4TlilAPnD_xhjNS          NaN       NaN        NaN       NaN   NaN    NaN   
AVpfvieo1cnluZ0-qdnu          NaN       NaN        NaN       NaN   NaN    NaN   

reviews_username      11111111aaaaaaaaaaaaaaaaa  1234  1234561  1234567  \
id                                                                        
AV13O1A8GV-KLJ3akUyj                        NaN   NaN      NaN      NaN   
AV14LG0R-jtxr-f38QfS                        NaN   NaN      NaN      NaN   
AV16khLE-jtxr-f38VFn                        NaN   NaN      NaN      NaN   
AV1YGDqsGV-KLJ3adc-O                        NaN   NaN      NaN      NaN   
AV1YIch7GV-KLJ3addeG                        NaN   NaN      NaN      NaN   
...                                         ...   ...      ...      ...   
AVpfshNsLJeJML43CB8q                        NaN   NaN      NaN      NaN   
AVpfthSailAPnD_xg3ON                        NaN   NaN      NaN      NaN   
AVpftikC1cnluZ0-p31V                        NaN   NaN      NaN      NaN   
AVpfv4TlilAPnD_xhjNS                        NaN   NaN      NaN      NaN   
AVpfvieo1cnluZ0-qdnu                        NaN   NaN      NaN      NaN   

reviews_username      123cat123  123charlie  123numbers  123rs  123soccermom  \
id                                                                             
AV13O1A8GV-KLJ3akUyj        NaN         NaN         NaN    NaN           NaN   
AV14LG0R-jtxr-f38QfS        NaN         NaN         NaN    NaN           NaN   
AV16khLE-jtxr-f38VFn        NaN         NaN         NaN    NaN           NaN   
AV1YGDqsGV-KLJ3adc-O        NaN         NaN         NaN    NaN           NaN   
AV1YIch7GV-KLJ3addeG        NaN         NaN         NaN    NaN           NaN   
...                         ...         ...         ...    ...           ...   
AVpfshNsLJeJML43CB8q        NaN         NaN         NaN    NaN           NaN   
AVpfthSailAPnD_xg3ON        NaN         NaN         NaN    NaN           NaN   
AVpftikC1cnluZ0-p31V        NaN         NaN         NaN    NaN           NaN   
AVpfv4TlilAPnD_xhjNS        NaN         NaN         NaN    NaN           NaN   
AVpfvieo1cnluZ0-qdnu        NaN         NaN         NaN    NaN           NaN   

reviews_username  

In [54]:
item_correlation_df_3[item_correlation_df_3<0]=0

common_item_predicted_ratings = np.dot(item_correlation_df_3, common_item_based_matrix.fillna(0))
common_item_predicted_ratings

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.28655752e-03, 1.28655752e-03, 1.28655752e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [55]:
dummy_test = common.copy()
dummy_test[value_column] = dummy_test[value_column].apply(lambda x: 1 if x>=1 else 0)
dummy_test = pd.pivot_table(dummy_test, index=product_column, columns=user_column, values=value_column).fillna(0)
common_item_predicted_ratings = np.multiply(common_item_predicted_ratings,dummy_test)

In [56]:
common_ = pd.pivot_table(common,index=product_column, columns=user_column, values=value_column)


In [57]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = common_item_predicted_ratings.copy()
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))

print(y)

MinMaxScaler(feature_range=(1, 5))
[[nan nan nan ... nan nan nan]
 [nan nan  1. ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]


In [58]:
# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

RMSE (Root Mean Square Error) for Item-Item recommendation system

In [59]:
rmse_item_item = (sum(sum((common_ - y )**2))/total_non_nan)**0.5
print(rmse_item_item)

3.5699746380356063


### Best-suited Recommendation model

* To get the best recommendation model, we will use RMSE (Root Mean Square Error) scores for both user-user and item-item based recommendation systems and do a comparison of the values.
* The recommendation model with the least RMSE will be selected as the best recommendation model.

In [60]:
# Recommended model evaluation
if rmse_user_user < rmse_item_item:
  print("Best-fit model is user-user recommendation system")
else:
  print("Best-fit model is item-item recommendation system")

Best-fit model is user-user recommendation system


On comparing the RMSE values of User Based Recommender and Item Based Recommender, User based recommendation model seems to be better in this case, as it has a lower RMSE value (~2)



In [61]:
# saving the correlation matrix of user based recommender
import pickle # Import the pickle module
pickle.dump(user_final_rating, open("user_final_rating.pkl", 'wb'))

## Top 5 Product recommendations to the user by the best recommendation model (user-user based recommendation system)

Recommendation of 20 products and filtering by sentiment model
Get the top 20 product recommendations using the recommender system and get the top 5 using the sentiment ML model.. the similar method would be used in model.py

In [62]:
import pickle

# Specify the paths to your .pkl files
cleaned_data_pkl = 'cleaned-data.pkl'
tfidf_vectorizer_pkl = 'tfidf-vectorizer.pkl'
sentiment_model_pkl = 'best-sentiment-classification-model.pkl'
recommendation_pkl = 'user_final_rating.pkl'

# Load the cleaned data
with open(cleaned_data_pkl, 'rb') as file:
    df_clean = pickle.load(file)

# Load the TF-IDF vectorizer
with open(tfidf_vectorizer_pkl, 'rb') as file:
    tfidf_vectorizer = pickle.load(file)

# Load the sentiment classification model
with open(sentiment_model_pkl, 'rb') as file:
    best_sentiment_model = pickle.load(file)

# Load the user recommendations model
with open(recommendation_pkl, 'rb') as file:
    user_final_rating = pickle.load(file)


In [63]:
def get_sentiment_recommendations(user, model):
    if user in user_final_rating.index:
        # Get the top 20 product recommendations for the user
        recommendations = (
            user_final_rating.loc[user]
            .sort_values(ascending=False)
            .index[:20]
        )

        # Filter the cleaned data for the recommended products
        recommended_products = df_clean[df_clean.id.isin(recommendations)]

        # Transform the input data using the saved TF-IDF vectorizer
        X = tfidf_vectorizer.transform(recommended_products["reviews_lemmatized"].values.astype(str))

        # Predict sentiment for the reviews
        recommended_products["predicted_sentiment"] = model.predict(X)

        # Select relevant columns for analysis
        recommended_products = recommended_products[['name', 'predicted_sentiment']]

        # Group by product name and calculate sentiment statistics
        sentiment_summary = recommended_products.groupby('name', as_index=False).agg(
            total_review_count=('predicted_sentiment', 'count'),
            pos_review_count=('predicted_sentiment', lambda x: (x == 1).sum())
        )

        # Calculate the positive sentiment percentage
        sentiment_summary['pos_sentiment_percent'] = np.round(
            sentiment_summary['pos_review_count'] / sentiment_summary['total_review_count'] * 100, 2
        )

        # Return the top 5 recommended products sorted by positive sentiment percentage
        return sentiment_summary.sort_values('pos_sentiment_percent', ascending=False).head(5)
    else:
        print(f"User name '{user}' doesn't exist")


In [64]:
get_sentiment_recommendations("rebecca", best_sentiment_model)

name  total_review_count  \
5             Clorox Disinfecting Bathroom Cleaner                2039   
1     Bounce Dryer Sheets, Fresh Linen, 160 sheets                  87   
17  The Resident Evil Collection 5 Discs (blu-Ray)                 845   
11                  Jason Aldean - They Don't Know                 204   
16                Red (special Edition) (dvdvideo)                 672   

    pos_review_count  pos_sentiment_percent  
5               2018                  98.97  
1                 86                  98.85  
17               817                  96.69  
11               197                  96.57  
16               648                  96.43

In [65]:
get_sentiment_recommendations("manny", best_sentiment_model)

name  \
5      Clorox Disinfecting Wipes Value Pack Scented 150 Ct Total   
4                           Clorox Disinfecting Bathroom Cleaner   
16  Stargate (ws) (ultimate Edition) (director's Cut) (dvdvideo)   
11                                Jason Aldean - They Don't Know   
15                              Red (special Edition) (dvdvideo)   

    total_review_count  pos_review_count  pos_sentiment_percent  
5                 8545              8497                  99.44  
4                 2039              2018                  98.97  
16                 186               181                  97.31  
11                 204               197                  96.57  
15                 672               648                  96.43

In [66]:
X_sample = tfidf_vectorizer.transform(["Awesome product, will recommend"])
y_pred_sample = best_sentiment_model.predict(X_sample)
y_pred_sample

array([1])

In [67]:
X_sample = tfidf_vectorizer.transform(["worst product, quality is poor"])
y_pred_sample = best_sentiment_model.predict(X_sample)
y_pred_sample


array([0])